;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua--prefix-override-handler
        cua-delete-region
        cua-paste
        python-indent-dedent-line-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-set-region
        paredit-forward-delete
        query-replace
        ))
